#!/usr/bin/env bash
# This script configures a new Ubuntu machine
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e 'Hello World!' > /var/www/html/index.ngnix-debian.html
sudo service ngnix restart
