#!/usr/bin/env bash
# Loops from 1 to 20
i=1
while ((i < 21))
do
	case $i in
		4|9|17)
			if ((i == 4))
			then
				echo $i
				echo "bad luck from China"
			elif ((i == 9))
			then
				echo $i
				echo "good luck from Japan"
			elif ((i == 17))
			then
				echo $i
				echo "bad luck from Italy"
			fi
			;;
		*)
			echo $i
			;;
	esac
	((i++))
done
