#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
h=0
m=0
while ((h < 13))
do
	while ((m < 60))
	do
		if ((m == 0))
		then
			echo "Hour: $h"
		else
			echo $m
		fi
		((m++))
	done
	((h++))
	m=0
done
