#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
h=0
m=0
echo "Hour: $h"
((m++))
while [ $m -le 60 ]
do
	if [ $h -eq 12 ]
	then
		x=1
		while [ $x -lt 60 ]
		do
			echo "$x"
			((x++))
		done
		break
	fi
	if [ $m -eq 60 ]
	then
		((h++))
		m=1
		echo "Hour: $h"
	else
		echo "$m"
		((m++))
	fi
done
		
